
services:
  angularapp:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 4200:4200
  aspnetapp:
    build:
      context: .
      target: final
    ports:
      - 8080:8080

