services:
  angularapp:
    build:
      context: ./angularapp
    environment:
      NODE_ENV: production
    ports:
      - 4200:4200
  aspnetapp:
    build:
      context: ./aspnetapp
    ports:
      - 8080:8080

